# -*- coding: utf-8 -*-
"""
Created on Fri Apr  3 20:17:38 2026

@author: Wang Junhao
"""

import os
import shutil
import subprocess
import ase.io
from rarepyth.utils import make_target_dir
from rarepyth.mace.data_io import split_xyz, merge_xyz

if __name__ == "__main__":
    # 1. Read parameters from data_source.txt generated by it3_train.py
    config = {}
    with open('data_source.txt', 'r') as f:
        for line in f:
            if '=' in line:
                key, val = line.strip().split('=', 1)
                config[key] = val

    all_set_dir = config.get('ALL_SET_DIR')
    _iter = int(config.get('CURRENT_ITER', 0))

    # The script runs in work_TIMESTAMP/train/, so root is two levels up
    root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
    filtered_checkpoints_dir = os.path.join(root_dir, 'filtered_checkpoints')
    iter_path = os.path.join(root_dir, 'ITER')

    # 2. Determine Foundation Model
    foundation_model = os.path.join(filtered_checkpoints_dir, 'mace_mp_medium.model')
    if _iter > 0:
        prev_model = os.path.join(filtered_checkpoints_dir, f'iter{_iter - 1}_fold_0.model')
        if os.path.exists(prev_model):
            foundation_model = prev_model

    if not os.path.exists(foundation_model):
        raise FileNotFoundError(f"Foundation model not found: {foundation_model}")

    # 3. Prepare Data using mace_data_io
    data_dir = 'kfold_data'
    make_target_dir(data_dir)

    merged_file_name = f"iter{_iter}_all_merged.xyz"
    merge_xyz(all_set_dir, data_dir, output_name=merged_file_name)
    merged_file_path = os.path.join(data_dir, merged_file_name)

    # Split the merged dataset into k distinct folds
    fold_files = split_xyz(merged_file_path, data_dir, method='folds', value=5)

    print("\n========================================")
    print("Starting Training")
    print("========================================\n")

    # Determine valid and train files for the current fold
    valid_file = fold_files[0]
    train_files_list = fold_files[1:]

    train_file_name = 'train.xyz'
    merge_xyz(train_files_list, data_dir, output_name=train_file_name)
    train_file = os.path.join(data_dir, train_file_name)

    model_name = f'ft_iter{_iter}'

    # ==========================================
    # Dynamic Parameter Scaling based on Dataset Size
    # ==========================================

    # Fast counting of structures in the current training set
    try:
        num_structures = sum(1 for _ in ase.io.iread(train_file, format='extxyz'))
    except Exception:
        num_structures = 400  # Safe fallback

    print(f"  -> Detected {num_structures} structures in training set. Adjusting hyperparameters...")

    # Heuristics for Active Learning scale-up
    if num_structures < 200:
        dyn_batch_size = 2
        dyn_epochs = 300
    elif num_structures < 1000:
        dyn_batch_size = 4
        dyn_epochs = 300
    elif num_structures < 3000:
        dyn_batch_size = 8
        dyn_epochs = 200
    elif num_structures < 10000:
        dyn_batch_size = 16
        dyn_epochs = 150
    else:
        dyn_batch_size = 32
        dyn_epochs = 120

    dyn_valid_batch_size = dyn_batch_size * 2

    # Start SWA at 80% of the total epochs
    dyn_start_swa = int(dyn_epochs * 0.8)

    # ==========================================
    # Build Command
    # ==========================================
    cmd = [
        "mace_run_train",
        f"--name={model_name}",
        f"--train_file={train_file}",
        f"--valid_file={valid_file}",
        f"--foundation_model={foundation_model}",
        "--E0s=average",
        "--energy_key=energy",
        "--forces_key=forces",

        # ==========================================
        # Core Modification 1: Weights & Learning Rate
        # ==========================================
        "--energy_weight=100.0",
        "--forces_weight=1.0",        # [Modified] Forces the model to prioritize fitting energy differences across different adsorption sites.
        "--lr=0.002",                 # [Modified] Set to 0.002 to ensure stable descent with high energy weight and small/medium batch sizes.

        # ==========================================
        # Core Modification 2: Dynamic Iteration Logic
        # ==========================================
        f"--batch_size={dyn_batch_size}",             # [Dynamic] Scaled based on dataset size to prevent 1-step epochs on small datasets.
        f"--valid_batch_size={dyn_valid_batch_size}",  # [Dynamic] Typically set to 2x train batch size.
        f"--max_num_epochs={dyn_epochs}",             # [Dynamic] Smaller datasets require more epochs to fully converge.
        f"--start_swa={dyn_start_swa}",               # [Dynamic] Set to 80% of max_epochs. Preserves SWA benefits while avoiding early LR jumps.
        "--swa_lr=0.0005",                            # [Retained] Explicitly restrict SWA learning rate to prevent gradient explosions.

        # [Deleted] "--ema" and "--ema_decay=0.99" are removed.
        # Exponential Moving Average causes severe mean drift on small AL datasets and micro-batches.

        # ==========================================
        # Base Environment & Architecture
        # ==========================================
        "--amsgrad",
        '--default_dtype=float64',
        "--device=cuda",
        "--enable_cueq=True",
        "--seed=42",
        "--max_L=2",                  # [Retained] High-order tensor features to greatly enhance angular resolution for bond angles.
        "--num_interactions=3"        # [Retained] Increased message passing layers to expand the receptive field into the deep surface.
    ]

    # Execute training command
    subprocess.run(cmd, check=True)

    # 5. Backup the trained model to the global checkpoints directory
    local_trained_model_path = f"{model_name}_stagetwo.model"
    trained_model_path = f"{model_name}.model"
    if os.path.exists(trained_model_path):
        shutil.copy(trained_model_path, os.path.join(filtered_checkpoints_dir, trained_model_path))
        print(f"Successfully saved {trained_model_path} to checkpoints.")
    else:
        print(f"Warning: Expected output model {trained_model_path} not found.")

    # 6. Increment global ITER counter
    with open(iter_path, 'w') as file:
        file.write(str(_iter + 1))
